apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecs-project-deploy
  labels:
    name: ecs-project-deploy
    app: shopping-app
spec: 
  replicas: 2
  selector:
    matchLabels:
      name: shopping-app-pod
      app: shopping-app
  template:
    metadata: 
      labels:
        name: shopping-app-pod
        app: shopping-app
    spec:
      containers:
      - name: shopping-app
        image: violinist999/ecs-php-bootcamp:1
        ports:
        - containerPort: 80